### ISSUE TITLE
CleanArchitecture deployment with docker

### ISSUE THREAD

**Issue by algarciatech** [jasontaylordev/CleanArchitecture#342]
Hi, I am trying to deploy my application using docker to create an image for azure AKS, the problem is that when finishing the construction of the image successfully and generating a container with it, I receive the following output and I don't know how to solve it:

> Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Intranet_CourseManager.Presentation.Startup.<ConfigureServices>b__4_5(CorsPolicyBuilder builder) in /app/Intranet_CourseManager/src/Presentation/Startup.cs:line 56
         at Microsoft.AspNetCore.Cors.Infrastructure.CorsOptions.AddPolicy(String name, Action`1 configurePolicy)
         at Intranet_CourseManager.Presentation.Startup.<ConfigureServices>b__4_3(CorsOptions options) in /app/Intranet_CourseManager/src/Presentation/Startup.cs:line 56
         at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
         at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
         at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
         at System.Lazy`1.CreateValue()
         at System.Lazy`1.get_Value()
         at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
         at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
         at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
         at Microsoft.AspNetCore.Cors.Infrastructure.CorsService..ctor(IOptions`1 options, ILoggerFactory loggerFactory)
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
         at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
         at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_0.<UseMiddleware>b__0(RequestDelegate next)
         at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)

I leave you the configuration of the docker and the Startup:

`FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app

COPY *.sln ./
COPY ./src/Application/*.csproj ./Application/
COPY ./src/Domain/*.csproj ./Domain/
COPY ./src/Infrastructure/*.csproj ./Infrastructure/
COPY ./src/Presentation/*.csproj ./Presentation/

COPY NuGet.config ./
COPY . .
WORKDIR /app/Application
RUN echo 'aplicacion'
RUN dotnet build -c Release -o app/
WORKDIR /app/Domain
RUN echo 'dominio'
RUN dotnet build -c Release -o app/
RUN echo 'infraestructura'
WORKDIR /app/Infrastructure
RUN dotnet build -c Release -o app/

WORKDIR /app
RUN dotnet restore --configfile NuGet.config

COPY . ./Intranet_CourseManager/
WORKDIR /app/Intranet_CourseManager
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime
EXPOSE 80
WORKDIR /app
COPY --from=build /app/Intranet_CourseManager/out .
ENTRYPOINT ["dotnet", "Intranet_CourseManager.Presentation.dll"]
`

MY STARTUP FILE line error:
` services.AddCors(options =>
            {
                options.AddPolicy("CorsPolicy", builder => builder
                    .WithOrigins(Configuration.GetSection("Settings:CorsAllowedDomains")?.Value.Split(";"))
                    .AllowAnyMethod()
                    .AllowAnyHeader());
                //.AllowCredentials());
            });
`

**Comment by RogerBarreto** [comment]
Ensure your environment variable instead of using the ":" uses double underscore.
ie: Settings__CorsAllowedDomains = "your domains"

**Comment by GFoley83** [comment]
@algarciatech did Roger's suggestion fix your problem? 
There is a known issue where you do have to replace colons with double underscores with containers running on Linux:

https://github.com/MicrosoftDocs/azure-docs/issues/60229
https://docs.microsoft.com/en-us/azure/app-service/configure-common#add-or-edit

**Comment by jasontaylordev** [comment]
FYI I have removed support for docker as per #630
