### ISSUE TITLE
issue with migration on latest template

### ISSUE THREAD

**Issue by bramburn** [jasontaylordev/CleanArchitecture#605]
**Describe the bug**
hi when I create a new entity and request for it to be built I am getting this error:

```shell
PS C:\dev\web2> dotnet ef migrations add "SampleMigration" --project src\Infrastructure --startup-project src\WebUI --output-dir Persistence\Migrations
Build started...
Build succeeded.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 6.0.0 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.InMemory:6.0.0' with options: StoreName=Web2Db
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Migrations.IMigrator'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.DesignTimeServiceCollectionExtensions.<>c__DisplayClass1_0.<AddDbContextDesignTimeServices>b__9(IServiceProvider _)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.EnsureServices(IServiceProvider services)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Migrations.IMigrator'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
```

**To Reproduce**

create a new entity

```cs
namespace Web2.Domain.Entities;

public class Product:AuditableEntity
{
    public int Id { get; set; }

    public int Name { get; set; }
}
```

register it in the applicationdbcontext.cs
```cs
    public DbSet<Product> Products  => Set<Product>();
```

even in the IApplicationDbContext interfance
```cs
    DbSet<Product> Products { get; }

```

after all that is done run the following commands in the root of the app

```shell
 dotnet ef migrations add "SampleMigration" --project src\Infrastructure --startup-project src\WebUI --output-dir Persistence\Migrations
```

**Expected behavior**
at least the migrations are built under the correct folders.
This is a fresh template that I've just used. Not sure where I am going wrong.

I thought that is how you add new entities.

**Screenshots**
![image](https://user-images.githubusercontent.com/11090413/162531210-cef4b5a7-a484-4543-933b-1964a166ce68.png)
![image](https://user-images.githubusercontent.com/11090413/162531262-cb5c496b-6e20-47b5-a748-c4226620e16f.png)
![image](https://user-images.githubusercontent.com/11090413/162531338-d2a1aa24-c334-435e-8c36-36fe16437668.png)
![image](https://user-images.githubusercontent.com/11090413/162531377-d640498f-9536-4c01-9457-38ecb939e6a1.png)

**Additional context**

**Comment by bramburn** [comment]
related to this https://github.com/jasontaylordev/CleanArchitecture/issues/105

I was able to resolve it, but this is a temporary patch, a note should be placed on the docs for this

**Comment by jasontaylordev** [comment]
InMemory database is enabled by default, so that it is easy to get the app up and running.
I'll make a not to update the docs.
