### ISSUE TITLE
Failed to run application

### ISSUE THREAD

**Issue by michael-pitz-snkeos** [jasontaylordev/CleanArchitecture#794]
**Describe the bug**
When I try to run application, I get an error

**To Reproduce**
1. dotnet new install Clean.Architecture.Solution.Template
2.  mkdir ca
3.  cd .\ca\
4. dotnet new ca-sln
5. cd .\src\WebUI\
6. 'dotnet run'
7. open browser on https://localhost:5001

Error message:
```
fail: Microsoft.AspNetCore.SpaProxy.SpaProxyLaunchManager[0]
      Couldn't start the SPA development server with command 'npm start'.
```

8. hit Ctrl-C
9. cd src\WebUI\ClientApp
10. npm start

Error message:
```
> ng serve --port 44447 --ssl --ssl-cert "%APPDATA%\ASP.NET\https\%npm_package_name%.pem" --ssl-key "%APPDATA%\ASP.NET\https\%npm_package_name%.key"


Initial Chunk Files | Names         |  Raw Size
vendor.js           | vendor        |   3.03 MB |
main.js             | main          | 193.71 kB |
polyfills.js        | polyfills     | 110.07 kB |
runtime.js          | runtime       |   6.37 kB |
styles.js           | styles        |   5.81 kB |

                    | Initial Total |   3.33 MB

Build at: 2023-02-09T10:10:34.190Z - Hash: 684321b27d10ba31 - Time: 9933ms

./src/styles.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
   ╷
23 │ @import "~bootstrap/scss/bootstrap";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src\styles.scss 23:9  root stylesheet

../../../../../../C#/Temp/ca/src/WebUI/ClientApp/src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
   ╷
23 │ @import "~bootstrap/scss/bootstrap";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src\styles.scss 23:9  root stylesheet

Error: Module not found: Error: Can't resolve 'C:/Users/michael.pitz/Workspace/C#/Temp/ca/src/WebUI/ClientApp/src/api-authorization/login-menu/login-menu.component.scss?ngResource' in 'C:\Users\michael.pitz\Workspace\C#\Temp\ca\src\WebUI\ClientApp'

Error: Module not found: Error: Can't resolve 'C:/Users/michael.pitz/Workspace/C#/Temp/ca/src/WebUI/ClientApp/src/api-authorization/login/login.component.scss?ngResource' in 'C:\Users\michael.pitz\Workspace\C#\Temp\ca\src\WebUI\ClientApp'

Error: Module not found: Error: Can't resolve 'C:/Users/michael.pitz/Workspace/C#/Temp/ca/src/WebUI/ClientApp/src/api-authorization/logout/logout.component.scss?ngResource' in 'C:\Users\michael.pitz\Workspace\C#\Temp\ca\src\WebUI\ClientApp'

Error: Module not found: Error: Can't resolve 'C:/Users/michael.pitz/Workspace/C#/Temp/ca/src/WebUI/ClientApp/src/app/nav-menu/nav-menu.component.scss?ngResource' in 'C:\Users\michael.pitz\Workspace\C#\Temp\ca\src\WebUI\ClientApp'

Error: Module not found: Error: Can't resolve 'C:/Users/michael.pitz/Workspace/C#/Temp/ca/src/WebUI/ClientApp/src/app/todo/todo.component.scss?ngResource' in 'C:\Users\michael.pitz\Workspace\C#\Temp\ca\src\WebUI\ClientApp'

Error: Module not found: Error: Can't resolve 'C:\Users\michael.pitz\Workspace\C#\Temp\ca\src\WebUI\ClientApp\node_modules\webpack-dev-server\client\index.js?protocol=auto%3A&username=&password=&hostname=0.0.0.0&port=0&pathname=%2Fng-cli-ws&logging=info&reconnect=10' in 'C:\Users\michael.pitz\Workspace\C#\Temp\ca\src\WebUI\ClientApp'

Error: The loader "C:/Users/michael.pitz/Workspace/C#/Temp/ca/src/WebUI/ClientApp/src/api-authorization/login-menu/login-menu.component.scss" didn't return a string.

Error: The loader "C:/Users/michael.pitz/Workspace/C#/Temp/ca/src/WebUI/ClientApp/src/api-authorization/login/login.component.scss" didn't return a string.

Error: The loader "C:/Users/michael.pitz/Workspace/C#/Temp/ca/src/WebUI/ClientApp/src/api-authorization/logout/logout.component.scss" didn't return a string.

Error: The loader "C:/Users/michael.pitz/Workspace/C#/Temp/ca/src/WebUI/ClientApp/src/app/nav-menu/nav-menu.component.scss" didn't return a string.

Error: The loader "C:/Users/michael.pitz/Workspace/C#/Temp/ca/src/WebUI/ClientApp/src/app/todo/todo.component.scss" didn't return a string.



** Angular Live Development Server is listening on localhost:44447, open your browser on https://localhost:44447/ **


× Failed to compile.
node:internal/fs/utils:681
    throw err;
    ^

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received 'C:\\Users\\michael.pitz\\Workspace\\C\x00#\\Temp\\ca\\src\\WebUI\\ClientApp\\node_modules\\bootstrap\\scss'
    at readdir (node:fs:1417:10)
    at go$readdir (C:\Users\michael.pitz\Workspace\C#\Temp\ca\src\WebUI\ClientApp\node_modules\graceful-fs\graceful-fs.js:206:16)
    at Object.readdir (C:\Users\michael.pitz\Workspace\C#\Temp\ca\src\WebUI\ClientApp\node_modules\graceful-fs\graceful-fs.js:211:12)
    at C:\Users\michael.pitz\Workspace\C#\Temp\ca\src\WebUI\ClientApp\node_modules\watchpack\lib\DirectoryWatcher.js:548:7
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_INVALID_ARG_VALUE'
}

Node.js v18.14.0
```

Versions:
- Windows 10 21H2
- .net 7.0.2
- node v18.14.0
- angular 14.1.3

**Comment by pbojanczyk** [comment]
It's a total guess but have you tried to rename your "C#" subfolder to something else like "CSharp" ?

**Comment by michael-pitz-snkeos** [comment]
tried a different folder with no '#' and no spaces in folder name, now it works.
